[package]
name = "memex"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "memex"
path = "src/main.rs"

[dependencies]
memex-common = { path = "../common" }
memex-tasks = { path = "../tasks" }
memex-daemon = { path = "../daemon" }
anyhow.workspace = true
tokio.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
